name: CI-CD

on: 
    push:
      branches: ["main"]
    workflow_dispatch:

  jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
        - name: Passo 01
          run : echo "Baixar a base de código"
        - name: Passo 02
          run : echo "Criar a imagem dos Microserviços"
        - name: Passo 03
          run : echo "Subir as imagens para o repositório de imagens Docker (DockerHub)"

    CD:
      needs: CI
      runs-on: ubuntu-latest
      steps:
        - name: Passo 01
          run : echo "Baixar a base de código"
        - name: Passo 02
          run : echo "Autenticar na AWS"
        - name: Passo 03
          run : echo "Deploy dos Microsserviços no Kubernetes"
